# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='moderation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='showcased',
            field=models.BooleanField(default=False),
        ),
    ]
