# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
