# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('meeting', 'meeting'), ('website', 'website')]),
        ),
    ]
