# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collectionbase_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('approve_collection_items', 'Approve collection items'),)},
        ),
        migrations.AlterModelOptions(
            name='collectionbase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': (('approve_meeting_items', 'Approve meeting items'),)},
        ),
    ]
