# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('workflow', '0002_workflow_case_description'),
        ('api', '0002_auto_20171025_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
            ],
            options={
                'permissions': (('write', 'Write priviledges'),),
            },
        ),
        migrations.CreateModel(
            name='CollectionWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_groups', models.ManyToManyField(blank=True, related_name='authorized_collection_workflows', to='auth.Group')),
            ],
            options={
                'permissions': (('write', 'Write priviledges'),),
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='workflow',
        ),
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('none', 'none'), ('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('presentation', 'presentation'), ('dataset', 'dataset'), ('website', 'website'), ('event', 'event'), ('meeting', 'meeting'), ('talk', 'talk'), ('poster', 'poster')], max_length=200),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_workflows', to='api.Collection'),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_workflows', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_group', to='api.Collection'),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_group', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='authorized_collection_workflows', to='api.CollectionGroup'),
        ),
        migrations.AddField(
            model_name='collection',
            name='workflows',
            field=models.ManyToManyField(related_name='collections', through='api.CollectionWorkflow', to='workflow.Workflow'),
        ),
    ]
