# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171106_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionworkflow',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
