# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection_admins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('view_collection', 'View this collection'), ('add_item', 'Add a item to the collection'))},
        ),
    ]
