# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170810_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionbase',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='collectionbase',
            name='submission_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
