# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170810_1836'),
        ('api', '0002_auto_20170704_2042'),
    ]

    operations = [
    ]
