# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('none', 'none'), ('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('presentation', 'presentation'), ('website', 'website'), ('event', 'event'), ('meeting', 'meeting'), ('talk', 'talk'), ('poster', 'poster')], max_length=200),
        ),
    ]
