# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170818_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbase',
            name='collection_type',
            field=models.CharField(default='Meeting', max_length=50),
            preserve_default=False,
        ),
    ]
