# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171019_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('edit', 'Edit this item'), ('view', 'View this item'), ('approve', 'Approve this item'))},
        ),
    ]
