# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20170815_1758'),
        ('api', '0004_auto_20170818_1424'),
    ]

    operations = [
    ]
