# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-13 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171204_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='admins',
        ),
        migrations.AddField(
            model_name='collection',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
