# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20170824_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('none', 'none'), ('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('presentation', 'presentation'), ('website', 'website'), ('event', 'event')], max_length=200),
        ),
    ]
