# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171010_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
