# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171106_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('none', 'none'), ('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('presentation', 'presentation'), ('repository', 'repository'), ('website', 'website'), ('event', 'event'), ('meeting', 'meeting'), ('talk', 'talk'), ('poster', 'poster')], max_length=200),
        ),
    ]
