# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171213_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='showcased',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='item',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
