# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171019_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gravatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
