# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171214_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='showcased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
