# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171107_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected'), ('pending-visible', 'pending-visible'), ('pending-hidden', 'pending-hidden')], max_length=200, null=True),
        ),
    ]
