# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-03 18:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171214_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('moderate_collection', 'Moderate collection'), ('administrate_collection', 'Administrate collection'))},
        ),
        migrations.AddField(
            model_name='collection',
            name='admins',
            field=models.ManyToManyField(related_name='administrated_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
