# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171107_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionworkflow',
            name='authorized_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_collection_workflows', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='collectionworkflow',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_workflows', to='api.Collection'),
        ),
    ]
