# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171107_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='showcased',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
