# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 15:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180105_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='detail_view_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
