# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 18:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
