# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 21:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='api.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='CaseParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_parameters', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_stubs', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='parameters', through='workflow.CaseParameter', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=64)),
                ('cases', models.ManyToManyField(blank=True, related_name='parameter_aliases', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterStub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('CASE', 'Case'), ('WORKFLOW', 'Workflow'), ('GLOBAL', 'Global')], default='CASE', max_length=8)),
                ('cases', models.ManyToManyField(blank=True, related_name='stubs', through='workflow.CaseStub', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='sections', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('widget_type', models.CharField(max_length=24)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='widgets', to='workflow.Case')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflow.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('initialization_values', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('workflow_config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='section',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='parameterstub',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_stubs', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='parameteralias',
            name='parameter_stub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='workflow.ParameterStub'),
        ),
        migrations.AddField(
            model_name='parameteralias',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_aliases', to='workflow.Widget'),
        ),
        migrations.AddField(
            model_name='parameteralias',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_aliases', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='stub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.ParameterStub'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='casestub',
            name='stub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_stubs', to='workflow.ParameterStub'),
        ),
        migrations.AddField(
            model_name='caseparameter',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_parameters', to='workflow.Parameter'),
        ),
        migrations.AddField(
            model_name='case',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='workflow.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='parameterstub',
            unique_together=set([('workflow', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='casestub',
            unique_together=set([('case', 'stub')]),
        ),
        migrations.AlterUniqueTogether(
            name='caseparameter',
            unique_together=set([('case', 'parameter')]),
        ),
    ]
