# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='case_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
