# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
