# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170913_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetparametermapping',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_parameter_mappings', to='workflow.Case'),
        ),
    ]
