# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20171106_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('read', 'read'), ('execute', 'execute')]},
        ),
    ]
