# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171107_2250'),
        ('workflow', '0004_auto_20171106_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.Item'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.Item'),
        ),
        migrations.AlterField(
            model_name='parameterstub',
            name='scope',
            field=models.CharField(choices=[('CASE', 'Case'), ('WORKFLOW', 'Workflow'), ('GLOBAL', 'Global'), ('ITEM', 'Item')], default='CASE', max_length=8),
        ),
    ]
