# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170916_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Case'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='stub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.ParameterStub'),
        ),
    ]
