# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 18:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_parameterstub_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='workflow_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='initialization_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
